package uef.edu.vn.dao;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import uef.edu.vn.model.DashboardDTO;
import uef.edu.vn.model.MonthlyRevenueDTO;
import uef.edu.vn.model.TopTourDTO;
import uef.edu.vn.model.TourRevenueDTO;
import uef.edu.vn.utils.DBConnection;

/**
 * Data Access Object for dashboard and reporting statistics.
 */
public class DashboardDAO {

    /**
     * Fetches general overview statistics for the dashboard.
     *
     * @return DashboardDTO containing total counts and total revenue
     */
    public DashboardDTO getAllDashboardStats() {
        DashboardDTO stats = new DashboardDTO();

        String sqlUsers = "SELECT COUNT(*) FROM users";
        String sqlTours = "SELECT COUNT(*) FROM tours";
        String sqlBookings = "SELECT COUNT(*) FROM bookings";
        String sqlRevenue = "SELECT COALESCE(SUM(amount), 0) FROM payments WHERE payment_status = 'PAID'";

        try (Connection conn = DBConnection.getConnection()) {

            // 1. Get total users
            try (PreparedStatement stmt = conn.prepareStatement(sqlUsers); ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    stats.setTotalUsers(rs.getInt(1));
                }
            }

            // 2. Get total tours
            try (PreparedStatement stmt = conn.prepareStatement(sqlTours); ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    stats.setTotalTours(rs.getInt(1));
                }
            }

            // 3. Get total bookings
            try (PreparedStatement stmt = conn.prepareStatement(sqlBookings); ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    stats.setTotalBookings(rs.getInt(1));
                }
            }

            // 4. Get total revenue
            try (PreparedStatement stmt = conn.prepareStatement(sqlRevenue); ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    stats.setTotalRevenue(rs.getBigDecimal(1));
                }
            }

        } catch (SQLException e) {
            throw new RuntimeException("Failed to fetch dashboard stats", e);
        }

        return stats;
    }

    /**
     * Fetches revenue generated by each tour.
     *
     * @return List of TourRevenueDTO
     */
    public List<TourRevenueDTO> getRevenueByTour() {
        List<TourRevenueDTO> list = new ArrayList<>();
        String sql = """
                     SELECT t.tour_name, COALESCE(SUM(p.amount), 0) AS revenue
                     FROM tours t
                     LEFT JOIN bookings b ON t.tour_id = b.tour_id
                     LEFT JOIN payments p ON b.booking_id = p.booking_id AND p.payment_status = 'PAID'
                     GROUP BY t.tour_id, t.tour_name
                     ORDER BY revenue DESC
                     """;

        try (Connection conn = DBConnection.getConnection(); PreparedStatement stmt = conn.prepareStatement(sql); ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                list.add(new TourRevenueDTO(
                        rs.getString("tour_name"),
                        rs.getBigDecimal("revenue")
                ));
            }
        } catch (SQLException e) {
            throw new RuntimeException("Failed to fetch revenue by tour", e);
        }
        return list;
    }

    /**
     * Fetches the top 5 most booked tours based on total people/bookings.
     *
     * @return List of TopTourDTO
     */
    public List<TopTourDTO> getTopTours() {
        List<TopTourDTO> list = new ArrayList<>();
        String sql = """
             SELECT t.tour_name, 
                    COUNT(b.booking_id) AS booking_count, 
                    COALESCE(SUM(b.number_of_people), 0) AS total_people
             FROM tours t
             LEFT JOIN bookings b ON t.tour_id = b.tour_id
             GROUP BY t.tour_id, t.tour_name
             ORDER BY total_people DESC, booking_count DESC
             LIMIT 5
             """;

        try (Connection conn = DBConnection.getConnection(); PreparedStatement stmt = conn.prepareStatement(sql); ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                list.add(new TopTourDTO(
                        rs.getString("tour_name"),
                        rs.getInt("booking_count"),
                        rs.getInt("total_people")
                ));
            }
        } catch (SQLException e) {
            throw new RuntimeException("Failed to fetch top tours", e);
        }
        return list;
    }

    /**
     * Fetches monthly revenue for the current year. Ensures all 12 months are
     * present in the returned list, filling with 0 if no revenue exists.
     *
     * @return List of MonthlyRevenueDTO
     */
    public List<MonthlyRevenueDTO> getMonthlyRevenue() {
        List<MonthlyRevenueDTO> list = new ArrayList<>();
        Map<Integer, BigDecimal> monthlyData = new HashMap<>();

        // Initialize all 12 months with 0 revenue
        for (int i = 1; i <= 12; i++) {
            monthlyData.put(i, BigDecimal.ZERO);
        }

        String sql = """
                     SELECT MONTH(p.payment_date) AS month, COALESCE(SUM(p.amount), 0) AS revenue
                     FROM payments p
                     WHERE p.payment_status = 'PAID' AND YEAR(p.payment_date) = YEAR(CURDATE())
                     GROUP BY MONTH(p.payment_date)
                     ORDER BY month
                     """;

        try (Connection conn = DBConnection.getConnection(); PreparedStatement stmt = conn.prepareStatement(sql); ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                int month = rs.getInt("month");
                BigDecimal revenue = rs.getBigDecimal("revenue");
                monthlyData.put(month, revenue);
            }
        } catch (SQLException e) {
            throw new RuntimeException("Failed to fetch monthly revenue", e);
        }

        // Build list ordered by month 1 to 12
        for (int i = 1; i <= 12; i++) {
            list.add(new MonthlyRevenueDTO(i, monthlyData.get(i)));
        }

        return list;
    }
}
